<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="LogicLab.Application.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LogicLab.Domain\LogicLab.Domain.csproj" />
    <ProjectReference Include="..\LogicLab.Engine\LogicLab.Engine.csproj" />
    <ProjectReference Include="..\LogicLab.ProjectFormat\LogicLab.ProjectFormat.csproj" />
  </ItemGroup>
</Project>
