<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\LogicLab.Web\LogicLab.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="bunit" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="TUnit" />
    <PackageReference Include="TUnit.AspNetCore" />
    <PackageReference Include="TUnit.FsCheck" />
  </ItemGroup>
</Project>
