<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
    <IsPackable>false</IsPackable>

    <AnalysisLevel>10-recommended</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>

    <NuGetAuditMode>all</NuGetAuditMode>
    <NuGetAuditLevel>low</NuGetAuditLevel>
    <WarningsNotAsErrors>$(WarningsNotAsErrors);NU1901</WarningsNotAsErrors>

    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Romeo Ahmed</Authors>
    <Copyright>Copyright (c) Romeo Ahmed 2026</Copyright>
    <PackageProjectUrl>https://github.com/romeoahmed/logic-lab</PackageProjectUrl>
    <RepositoryUrl>https://github.com/romeoahmed/logic-lab</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT OR Apache-2.0</PackageLicenseExpression>
  </PropertyGroup>
</Project>
