<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
    <CentralPackageVersionOverrideEnabled>false</CentralPackageVersionOverrideEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="FsCheck" Version="3.3.4" />
    <PackageVersion Include="TUnit" Version="1.63.0" />
    <PackageVersion Include="TUnit.FsCheck" Version="1.63.0" />
  </ItemGroup>
</Project>
