<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Include="../LogicLab.ComponentTesting/CoreContractFixture.cs" Link="Fixtures/CoreContractFixture.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\LogicLab.Domain\LogicLab.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FsCheck" />
    <PackageReference Include="TUnit" />
    <PackageReference Include="TUnit.FsCheck" />
  </ItemGroup>
</Project>
