<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\LogicLab.ProjectFormat\LogicLab.ProjectFormat.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FsCheck" />
    <PackageReference Include="TUnit" />
    <PackageReference Include="TUnit.FsCheck" />
  </ItemGroup>
</Project>
