<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="TUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\LogicLab.Infrastructure\LogicLab.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\LogicLab.Application\LogicLab.Application.csproj" />
  </ItemGroup>
</Project>
