// <auto-generated />
using LogicLab.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogicLab.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LogicLabDbContext))]
    [Migration("20260808140110_InitialDurableProjects")]
    partial class InitialDurableProjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("LogicLab.Infrastructure.Persistence.DurableCommandReceiptRecord", b =>
                {
                    b.Property<long>("ReceiptSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("receipt_sequence");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("workspace_id");

                    b.Property<string>("AttachmentGeneration")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("attachment_generation");

                    b.Property<string>("ClientIntentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("client_intent_id");

                    b.Property<string>("ActualDurableVersion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("actual_durable_version");

                    b.Property<string>("CommandFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("command_fingerprint");

                    b.Property<string>("CommandKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("command_kind");

                    b.Property<string>("DurableProjectId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("durable_project_id");

                    b.Property<string>("DurableVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("durable_version");

                    b.Property<string>("ExpectedDurableVersion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("expected_durable_version");

                    b.Property<string>("OutcomeKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("outcome_kind");

                    b.Property<string>("ProjectRevisionId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("project_revision_id");

                    b.HasKey("ReceiptSequence");

                    b.HasIndex("DurableProjectId");

                    b.HasIndex(new[] { "WorkspaceId", "AttachmentGeneration", "ClientIntentId" }, "ux_durable_command_receipts_workspace_generation_intent")
                        .IsUnique();

                    b.ToTable("durable_command_receipts", (string)null);
                });

            modelBuilder.Entity("LogicLab.Infrastructure.Persistence.DurableProjectRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("durable_project_id");

                    b.Property<string>("CurrentProjectRevisionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("current_project_revision_id");

                    b.Property<string>("ClaimWorkspaceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("claim_workspace_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<byte[]>("DisplayNameSortKey")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("display_name_sort_key");

                    b.Property<string>("DurableVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("durable_version");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("subject_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DisplayNameSortKey", "Id" }, "ix_durable_projects_display_name_sort_key_id")
                        .IsUnique();

                    b.HasIndex(new[] { "ClaimWorkspaceId" }, "ux_durable_projects_claim_workspace_id")
                        .IsUnique();

                    b.ToTable("durable_projects", (string)null);
                });

            modelBuilder.Entity("LogicLab.Infrastructure.Persistence.ProjectRevisionRecord", b =>
                {
                    b.Property<string>("DurableProjectId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("durable_project_id");

                    b.Property<string>("ProjectRevisionId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("project_revision_id");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("payload");

                    b.HasKey("DurableProjectId", "ProjectRevisionId");

                    b.ToTable("project_revisions", (string)null);
                });

            modelBuilder.Entity("LogicLab.Infrastructure.Persistence.DurableCommandReceiptRecord", b =>
                {
                    b.HasOne("LogicLab.Infrastructure.Persistence.DurableProjectRecord", null)
                        .WithMany()
                        .HasForeignKey("DurableProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogicLab.Infrastructure.Persistence.ProjectRevisionRecord", b =>
                {
                    b.HasOne("LogicLab.Infrastructure.Persistence.DurableProjectRecord", null)
                        .WithMany()
                        .HasForeignKey("DurableProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
