<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\LogicLab.Presentation\LogicLab.Presentation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FsCheck" />
    <PackageReference Include="TUnit" />
    <PackageReference Include="TUnit.FsCheck" />
  </ItemGroup>
</Project>
